export const DEFAULT_QUESTIONS = {
  truth: [
    'What is the most embarrassing thing you have ever done on camera?',
    'Who is your celebrity crush and why?',
    'What is a weird habit you have that nobody knows about?',
    'Have you ever pretended to be busy to avoid a call? Who was it?',
    'What is the last thing you searched for on your phone?',
    'What is the most cringe message you have ever sent?',
    'Have you ever faked a laugh just to be polite? Tell us about it.',
    'What is the worst first date you have ever been on?',
    'What is a secret talent you are secretly proud of?',
    'Have you ever read someones text over their shoulder?',
    'What is your most embarrassing childhood memory?',
    'What song do you secretly sing in the shower?',
    'Have you ever hit reply all by accident? What happened?',
    'What is the weirdest thing you have ever eaten?',
    'Have you ever kept a wrong-number conversation going for fun?',
    'What is your most irrational fear?',
    'What is the dumbest thing you have ever bought online?',
    'Have you ever caught yourself talking to yourself in public?',
    'What is a rumor someone once started about you?',
    'What is the last thing you lied about?',
    'Have you ever been caught sneaking a snack late at night?',
    'What is your guilty-pleasure TV show or song?',
    'What is the most awkward thing you have ever said to a stranger?',
    'Have you ever waved back at someone who was not waving at you?',
    'What is your most-used emoji and why?',
    'Have you ever fallen asleep in a weird place?',
    'What is something you always say you will do but never actually do?',
    'What is the most embarrassing photo in your camera roll?',
    'Have you ever peeked at a gift before opening it?',
    'What is your worst haircut story?',
  ],
  dare: [
    'Do your best celebrity impression for 20 seconds.',
    'Speak in a pirate accent until the next question.',
    'Make your best caught-on-camera scared face.',
    'Read a sentence using only emojis, out loud, with full emotion.',
    'Do 10 jumping jacks while singing a song.',
    'Do a runway model walk across the room.',
    'Blow a kiss and say call me to the camera.',
    'Tell a joke while keeping a completely straight face.',
    'Dance like nobody is watching for 15 seconds.',
    'Say the alphabet backwards as fast as you can.',
    'Invent a brand-new dance move and give it a name.',
    'Compliment yourself out loud for 20 seconds.',
    'Do your best dramatic movie-trailer voice for the show.',
    'Wink at the camera and say you know it.',
    'Hold a plank for 20 seconds while counting out loud.',
    'Do a slow-motion hero run across the room.',
    'Pretend you just won an Oscar for 15 seconds.',
    'Speak only in a whisper for the next two questions.',
    'Make your best wow face and hold it for 10 seconds.',
    'Do your best robot dance for 15 seconds.',
    'Give a weather report using only animal sounds.',
    'Stand up and take a dramatic bow like you are famous.',
    'Mime brushing your teeth for 15 seconds, dramatically.',
    'Sing one line of your favorite song as loudly as you can.',
    'Do a dramatic slow-motion fall to the floor.',
    'Introduce yourself like you are on a dating show.',
    'Do 5 push-ups while keeping eye contact with the camera.',
    'Create a 30-second rap about FLOXI LIVE.',
    'Show your best unimpressed face for 10 seconds.',
    'Wave at the camera like you have not seen it in years.',
  ],
}

export const CATEGORIES = ['truth', 'dare']

export const CATEGORY_LABELS = {
  truth: 'TRUTH',
  dare: 'DARE',
}
